export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
  GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
  GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
};

export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

}

export const userConstants = {
  GET_INFO_USER_REQUEST: "GET_INFO_USER_REQUEST",
  GET_INFO_USER_FAILURE: "GET_INFO_USER_FAILURE",
  GET_INFO_USER_SUCCESS: "GET_INFO_USER_SUCCESS",

}

export const adminConstants = {
  GET_ALL_ADMIN_REQUEST: "GET_ALL_ADMIN_REQUEST",
  GET_ALL_ADMIN_SUCCESS: "GET_ALL_ADMIN_SUCCESS",
  GET_ALL_ADMIN_FAILURE: "GET_ALL_ADMIN_FAILURE",

  ADMIN_REGISTER_REQUEST: "ADMIN_REGISTER_REQUEST",
  ADMIN_REGISTER_SUCCESS: "ADMIN_REGISTER_SUCCESS",
  ADMIN_REGISTER_FAILURE: "ADMIN_REGISTER_FAILURE",

  DELETE_ONE_ADMIN_REQUEST: "DELETE_ONE_ADMIN_REQUEST",
  DELETE_ONE_ADMIN_SUCCESS: "DELETE_ONE_ADMIN_SUCCESS",
  DELETE_ONE_ADMIN_FAILURE: "DELETE_ONE_ADMIN_FAILURE",

  UPDATE_INFORMATION_SUCCESS: "UPDATE_INFORMATION_SUCCESS",

  CHANGE_INFORMATION_REQUEST: "CHANGE_INFORMATION_REQUEST",
  CHANGE_INFORMATION_SUCCESS: "CHANGE_INFORMATION_SUCCESS",
  CHANGE_INFORMATION_FAILURE: "CHANGE_INFORMATION_FAILURE",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",

};

export const customerConstants = {
  GET_ALL_CUSTOMER_REQUEST: "GET_ALL_CUSTOMER_REQUEST",
  GET_ALL_CUSTOMER_SUCCESS: "GET_ALL_CUSTOMER_SUCCESS",
  GET_ALL_CUSTOMER_FAILURE: "GET_ALL_CUSTOMER_FAILURE",

  CUSTOMER_REGISTER_REQUEST: "CUSTOMER_REGISTER_REQUEST",
  CUSTOMER_REGISTER_SUCCESS: "CUSTOMER_REGISTER_SUCCESS",
  CUSTOMER_REGISTER_FAILURE: "CUSTOMER_REGISTER_FAILURE",

  CUSTOMER_BLOCK_REQUEST: "CUSTOMER_BLOCK_REQUEST",
  CUSTOMER_BLOCK_SUCCESS: "CUSTOMER_BLOCK_SUCCESS",
  CUSTOMER_BLOCK_FAILURE: "CUSTOMER_BLOCK_FAILURE",
};

export const categoryConstants = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",

  ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
  ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
  ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",

  UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",

  DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_FAILURE",
};

export const categoryChildConstants = {
  GET_ALL_CATEGORY_CHILD_REQUEST: "GET_ALL_CATEGORY_CHILD_REQUEST",
  GET_ALL_CATEGORY_CHILD_SUCCESS: "GET_ALL_CATEGORY_CHILD_SUCCESS",
  GET_ALL_CATEGORY_CHILD_FAILURE: "GET_ALL_CATEGORY_CHILD_FAILURE",

  ADD_CATEGORY_CHILD_REQUEST: "ADD_CATEGORY_CHILD_REQUEST",
  ADD_CATEGORY_CHILD_SUCCESS: "ADD_CATEGORY_CHILD_SUCCESS",
  ADD_CATEGORY_CHILD_FAILURE: "ADD_CATEGORY_CHILD_FAILURE",

  UPDATE_CATEGORY_CHILD_REQUEST: "UPDATE_CATEGORY_CHILD_REQUEST",
  UPDATE_CATEGORY_CHILD_SUCCESS: "UPDATE_CATEGORY_CHILD_SUCCESS",
  UPDATE_CATEGORY_CHILD_FAILURE: "UPDATE_CATEGORY_CHILD_FAILURE",

  DELETE_CATEGORY_CHILD_REQUEST: "DELETE_CATEGORY_CHILD_REQUEST",
  DELETE_CATEGORY_CHILD_SUCCESS: "DELETE_CATEGORY_CHILD_SUCCESS",
  DELETE_CATEGORY_CHILD_FAILURE: "DELETE_CATEGORY_CHILD_FAILURE",
};

export const brandConstants = {
  GET_ALL_BRAND_REQUEST: "GET_ALL_BRAND_REQUEST",
  GET_ALL_BRAND_SUCCESS: "GET_ALL_BRAND_SUCCESS",
  GET_ALL_BRAND_FAILURE: "GET_ALL_BRAND_FAILURE",

  ADD_BRAND_REQUEST: "ADD_BRAND_REQUEST",
  ADD_BRAND_SUCCESS: "ADD_BRAND_SUCCESS",
  ADD_BRAND_FAILURE: "ADD_BRAND_FAILURE",

  UPDATE_BRAND_REQUEST: "UPDATE_BRAND_REQUEST",
  UPDATE_BRAND_SUCCESS: "UPDATE_BRAND_SUCCESS",
  UPDATE_BRAND_FAILURE: "UPDATE_BRAND_FAILURE",

  DELETE_BRAND_REQUEST: "DELETE_BRAND_REQUEST",
  DELETE_BRAND_SUCCESS: "DELETE_BRAND_SUCCESS",
  DELETE_BRAND_FAILURE: "DELETE_BRAND_FAILURE",
};

export const productConstants = {
  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE",

  ADD_PRODUCT_REQUEST: "ADD_PRODUCT_REQUEST",
  ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
  ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",

  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",

  DELETE_PRODUCT_REQUEST: "DELETE_PRODUCT_REQUEST",
  DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
  DELETE_PRODUCT_FAILURE: "DELETE_PRODUCT_FAILURE",
};

export const productSkuConstants = {
  GET_ALL_PRODUCT_SKU_REQUEST: "GET_ALL_PRODUCT_SKU_REQUEST",
  GET_ALL_PRODUCT_SKU_SUCCESS: "GET_ALL_PRODUCT_SKU_SUCCESS",
  GET_ALL_PRODUCT_SKU_FAILURE: "GET_ALL_PRODUCT_SKU_FAILURE",

  ADD_PRODUCT_SKU_REQUEST: "ADD_PRODUCT_SKU_REQUEST",
  ADD_PRODUCT_SKU_SUCCESS: "ADD_PRODUCT_SKU_SUCCESS",
  ADD_PRODUCT_SKU_FAILURE: "ADD_PRODUCT_SKU_FAILURE",

  UPDATE_PRODUCT_SKU_REQUEST: "UPDATE_PRODUCT_SKU_REQUEST",
  UPDATE_PRODUCT_SKU_SUCCESS: "UPDATE_PRODUCT_SKU_SUCCESS",
  UPDATE_PRODUCT_SKU_FAILURE: "UPDATE_PRODUCT_SKU_FAILURE",

  DELETE_PRODUCT_SKU_REQUEST: "DELETE_PRODUCT_SKU_REQUEST",
  DELETE_PRODUCT_SKU_SUCCESS: "DELETE_PRODUCT_SKU_SUCCESS",
  DELETE_PRODUCT_SKU_FAILURE: "DELETE_PRODUCT_SKU_FAILURE",
};

export const orderConstants = {
  GET_ALL_ORDER_REQUEST: "GET_ALL_ORDER_REQUEST",
  GET_ALL_ORDER_SUCCESS: "GET_ALL_ORDER_SUCCESS",
  GET_ALL_ORDER_FAILURE: "GET_ALL_ORDER_FAILURE",
}


export const masterConstants = {
  GET_ALL_MASTER_REQUEST: "GET_ALL_MASTER_REQUEST",
  GET_ALL_MASTER_SUCCESS: "GET_ALL_MASTER_SUCCESS",
  GET_ALL_MASTER_SIZE_SUCCESS: "GET_ALL_MASTER_SIZE_SUCCESS",
  GET_ALL_MASTER_COLOR_SUCCESS: "GET_ALL_MASTER_COLOR_SUCCESS",
  GET_ALL_MASTER_PRODUCT_STATUS_SUCCESS: "GET_ALL_MASTER_PRODUCT_STATUS_SUCCESS",
  GET_ALL_MASTER_FAILURE: "GET_ALL_MASTER_FAILURE",
}

export const dasboardConstants = {
  GET_ALL_DASHBOARD_REQUEST: "GET_ALL_DASHBOARD_REQUEST",
  GET_ALL_DASHBOARD_SUCCESS: "GET_ALL_DASHBOARD_SUCCESS",
  GET_ALL_DASHBOARD_FAILURE: "GET_ALL_DASHBOARD_FAILURE",
}